name: "Bug Report"
description: "Report a bug in the container runtime, image builder, CLI, or DSL (.ci)"
title: "[BUG] "
labels: ["bug"]

body:
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "Select the OS where the bug occurs"
      options:
        - Arch Linux
        - Ubuntu
        - macOS
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: "OS Version"
      description: "Exact version of the operating system"
      placeholder: "e.g., Arch Linux 2026.02.17"
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: "Hardware / System"
      description: "CPU, RAM, GPU"
      placeholder: "Ryzen 9 7950X, 64GB RAM"
    validations:
      required: true

  - type: input
    id: rust_version
    attributes:
      label: "Rust Version"
      placeholder: "e.g., 1.75.0 stable"
    validations:
      required: true

  - type: input
    id: container_commit
    attributes:
      label: "Container Commit / Version"
      placeholder: "Commit SHA or tag"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "Detailed Steps to Reproduce"
      placeholder: |
        1. Run `container build image.ci`
        2. Run `container run test`
        3. Crash happens
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Observed Behavior / Logs"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
