name: "Feature Request"
description: "Suggest a new feature for the container runtime"
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: input
    id: container_commit
    attributes:
      label: "Container Commit / Version"
      placeholder: "Commit SHA or tag"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the Feature"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Use Case / Motivation"
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: "Proposed Implementation"

  - type: input
    id: rust_version
    attributes:
      label: "Target Rust Version"
      placeholder: "e.g., 1.75.0 stable"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
